version: '3'
services:
  gnn-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./data:/app/data
      - ./grp:/app/grp
      - ./src:/app/src
      - ./raw:/app/raw