version: '3'
services:
  backend-server:
    build: .
    volumes:
      - ./SurveyCS:/app/SurveyCS
      - ./app_server.py:/app/app_server.py
      - ./search.txt:/app/search.txt
      - ./name2id.txt:/app/name2id.txt
      - ./converter.py:/app/converter.py
    ports:
      - 5000:5000